env: DB=postgres
language: node_js

install: "npm install"
script: "npm test"
node_js:
  - "0.10"
  - "0.12"
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - contact@stevemcarthur.co.uk
